spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  graphql:
    graphiql:
      enabled: true

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true


security:
  jwt:
    access: 1
    refresh: 30

springdoc:
  override-with-generic-response: false
