server:
  port: 9090
spring:
  application:
    name: parkme_server

  #   PostgreSQL connection
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  #  GraphQL
  graphql:
    graphiql:
      enabled: true

  #  Liquibase
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

security:
  jwt:
    access: 1
    refresh: 30

springdoc:
  override-with-generic-response: false
